version: '2'
services:
  pyutil:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
        - ./examples:/pyutil/examples
        - ./results:/pyutil/results
        - ./pyutil:/pyutil/pyutil

  # used to create test resources
  testdata:
     build:
       context: .
       dockerfile: Dockerfile

     volumes:
       - ./test/config.py:/pyutil/config.py
       - ./test/resources:/pyutil/resources

     command: python config.py



