version: '3.6'
services:
  pyutil:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    extra_hosts:
      - quantsrv:192.168.100.15
    env_file:
      - .config

  jupyter:
    build:
      context: .
      dockerfile: ./binder/Dockerfile
    volumes:
      - ./work:${WORK}
    extra_hosts:
      - quantsrv:192.168.100.15
    env_file:
      - .config
    ports:
      - ${PORT}:8888

