version: '3.4'
services:
  pyutil:
     build:
       context: .
       dockerfile: Dockerfile
       target: test
     volumes:
        - ./pyutil:/pyutil/pyutil
        - ./sandbox:/pyutil/sandbox
        -  /etc/localtime:/etc/localtime:ro
     extra_hosts:
        # obviously you can not access
        - quantsrv:192.168.100.15
     env_file:
       - .env
     environment:
       # used mainly for testing!
       - influxdb_host=test-influxdb
       - influxdb_db=test
     links:
       - test-influxdb
       - test-postgresql

  test-postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: "test"

  test-influxdb:
    image: influxdb:1.5.4
