version: '2'
services:
  pyutil:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
        - ./examples:/pyutil/examples
        - ./results:/pyutil/results
        - ./pyutil:/pyutil/pyutil
     extra_hosts:
        # obviously you can not access
        - quantsrv:192.168.100.15


