version: '2'
services:
  pyutil:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
        - ./examples:/pyutil/examples
        - ./results:/pyutil/results
        - ./pyutil:/pyutil/pyutil

  # used to create test resources
  test:
     build:
       context: .
       dockerfile: Dockerfile

     volumes:
       - ./test/data.py:/pyutil/data.py
       - ./test/resources:/pyutil/resources

     command: python data.py



