version: '2'
services:
  sut:
    build:
       context: .
       dockerfile: Dockerfile-Test
    command: nosetests --with-coverage --cover-package=pyutil
    links:
     - mongo
  mongo:
    image: mongo
    expose:
       - "27017"