version: '3.6'
services:
  pyutil:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    extra_hosts:
      - quantsrv:192.168.100.15

  jupyter:
    build:
      context: .
      dockerfile: ./binder/Dockerfile
    volumes:
      - ./binder/files:${WORK}
    extra_hosts:
      - quantsrv:192.168.100.15
    ports:
      - ${PORT}:8888

