version: '3.6'
services:
  test:
     build:
       context: .
       dockerfile: Dockerfile
       target: test

     volumes:
        - ./pyutil:/pyutil/pyutil:ro
        - ./test:/pyutil/test:ro
        - ./artifacts:/pyutil/artifacts
        - ./source:/source

     env_file:
       - test/.env-test

     links:
       - test-influxdb
       - test-postgresql
       - test-mongo

  test-postgresql:
    image: postgres:9.6

  test-influxdb:
    image: influxdb:1.5.4

  test-mongo:
    image: mongo:4.0.1

