version: '3.6'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      target: test

    volumes:
      - ./test:/pyutil/test:ro
      - ./artifacts:/pyutil/artifacts
      - ./source:/source

    links:
      - test-postgresql
      - test-mongo

    env_file:
      - ./test/.env-test

  test-postgresql:
    image: postgres:9.6

  test-mongo:
    image: bitnami/mongodb

    env_file:
      - ./test/.env-test
