version: '3.6'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      target: test

    volumes:
      - ./pyutil:/pyutil/pyutil:ro
      - ./test:/pyutil/test:ro
      - ./artifacts:/pyutil/artifacts
      - ./source:/source

    env_file:
      - test/.env-test

    links:
      - test-postgresql
      - test-mongo

  test-postgresql:
    image: postgres:9.6

  test-mongo:
    image: mongo
