version: '3.6'
services:
  pyutil:
     build:
       context: .
       dockerfile: Dockerfile
       target: builder
     volumes:
        - ./pyutil:/pyutil/pyutil:ro
     extra_hosts:
        - quantsrv:192.168.100.15
     env_file:
       - .env

  jupyter:
    build:
      context: .
      dockerfile: ./binder/Dockerfile
    volumes:
      #- ./pyutil:/home/jovyan/work/pyutil
      - ./jupyter_notebook_config.py:/etc/jupyter/jupyter_notebook_config.py:ro
      - ./work:/home/jovyan/work
      - ./pyutil:/home/jovyan/work/pyutil:ro
    extra_hosts:
      - quantsrv:192.168.100.15
    env_file:
      - .env

