version: '3.4'
services:
  pyutil:
     build:
       context: .
       dockerfile: Dockerfile
       target: test
     volumes:
        - ./pyutil:/pyutil/pyutil
        - ./sandbox:/pyutil/sandbox
     extra_hosts:
        # obviously you can not access
        - quantsrv:192.168.100.15
     env_file:
       - .env
     volumes:
        -  /etc/localtime:/etc/localtime:ro
     #command: ["/pyutil/wait-for-postgres.sh", "test-postgresql"]
     links:
       - test-postgresql

  test-postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: "test"