version: '3.6'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      target: test

    volumes:
      - ./pyutil:/pyutil/pyutil:ro
      - ./test:/pyutil/test:ro
      - ./artifacts:/pyutil/artifacts
      - ./source:/source

    environment:
      - MAILGUNAPI=0
      - MAILGUNKEY=0
