version: '3.4'
services:
  pyutil:
     build:
       context: .
       dockerfile: Dockerfile
       target: builder
     volumes:
        - ./pyutil:/pyutil/pyutil
        - ./sandbox:/pyutil/sandbox
        - /etc/localtime:/etc/localtime:ro
     extra_hosts:
        - quantsrv:192.168.100.15
     env_file:
       - .env

