version: '3.6'
services:
  test-pyutil:
     image: pyutil.test

     build:
       context: .
       dockerfile: Dockerfile
       target: test

     volumes:
        - ./pyutil:/pyutil/pyutil
        - ./test:/pyutil/test
        - ./sandbox:/pyutil/sandbox
        - ./html-coverage:/html-coverage
        - ./html-report:/html-report
        - ./source:/pyutil/source:ro
        - ./build:/pyutil/build

     env_file:
       - test/.env-test

     links:
       - test-influxdb
       - test-postgresql

  test-postgresql:
    image: postgres:9.6

  test-influxdb:
    image: influxdb:1.5.4

